### ISSUE TITLE
※commit 형식 ※

### ISSUE THREAD

**Issue by iopopoi** [iopopoi/tudac#2]
### git commit -m"**message"**

message형식

"[**fix**/**new**/**del**/**move**] : [**commit하는 내용에 대한 간단한 설명**] (enter)
 [**commit 내용에 대한 자세한 설명**]"

> 서로의 수정 내용을 가능한 쉽게 이해하기 위해 한번에 수정한 모든 파일을 올리기 보다는 같은 내용에 해당하는 것들을 나누어  add하면서 commit message를 작성해주세요.

**Comment by huskycat1202** [comment]
어차피 del, move는 fix에 포함되니깐
"[fix/new] : [commit하는 내용에 대한 간단한 설명] (enter)
[commit 내용에 대한 자세한 설명]"
으로 바꾸는게 더 간단하고 보기 편할 것 같아요!!

**Comment by kjmin622** [comment]
"[fix/new] : [code/image/....] // 옆은 예시, 한 두 단어로 설명
[추가 설명]"

**Comment by iopopoi** [comment]
"[fix/new] : [code/image/...+가장 상위 폴더이름] // 옆은 예시, 한 두 단어로 설명
[추가 설명]" 로 정하면 좋을것 같아요.

**Comment by Lee-SungMin** [comment]
저도 fix와 new로 크게 나누면 될 것 같습니다!
"[fix/new] : [commit하는 내용에 대한 간단한 설명] (enter)
[commit 내용에 대한 자세한 설명]"

**Comment by iopopoi** [comment]
"[fix/add] : [code/image/...+가장 상위 폴더이름] // 옆은 예시, 한 두 단어로 설명
[추가 설명]" 로 정하면 좋을것 같아요.
