### ISSUE TITLE
Question_Readme

### ISSUE THREAD

**Issue by iopopoi** [iopopoi/tudac#3]
Readme.md를 어떻게 구성해야 할까요?

**Comment by Lee-SungMin** [comment]
https://github.com/cheese10yun/github-project-management#zenhub-%EC%82%AC%EC%9A%A9%EB%B2%95
위 링크처럼 잘 정돈되어 있고, 목차 기능을 참고하면 매우 좋을 것 같아요!

**Comment by huskycat1202** [comment]
-프로젝트이름
-프로젝트 소개
-설치 방법
-사용 예제
-개발 환경 설정 방법
-기여 방법
-변경 로그
-라이센스 및 작성자 정보
이렇게 들어가는 거 어때요?

**Comment by kjmin622** [comment]
목차 기능은 링크를 동일 사이트의 id를 다는 방식으로 구현하면 될 것 같습니다!

**Comment by iopopoi** [comment]
네!! 의견 감사해요!! 
이슈닫을게요!
