### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by Lee-SungMin** [iopopoi/tudac#4]
![KakaoTalk_20200624_210907972](https://user-images.githubusercontent.com/55132964/85553537-03caeb80-b65f-11ea-8c50-406d5181be27.png)

작업을 위해 git pull 을 진행해야 하는데 error가 발생합니다...ㅠㅠ
어떻게 해결해야 할까요?

**Comment by iopopoi** [comment]
서버가 열려 있는 상태에서 git pull을 하는 게 문제 인것 같아요.
서버가 열려있는 경우 db를 다른사람이 수정후  git push를 한것을 받아오지 못하는 것 같아요.

**Comment by iopopoi** [comment]
서버를 닫고 git pull하면 될것 같아요!

**Comment by kjmin622** [comment]
https://stackoverflow.com/questions/11774397/git-push-error-unable-to-unlink-old-permission-denied
여기에 따르면 iopopoi님 말씀대로 그 링크의 프로세스가 실행중일 가능성이 가장 크다고 합니다.

**Comment by Lee-SungMin** [comment]
오 감사합니다!! 해결됐어요!! 서버를 켜놔서 생긴 문제였군요.. ㅠㅠ
