### ISSUE TITLE
사용예제 형식

### ISSUE THREAD

**Issue by huskycat1202** [iopopoi/tudac#5]
사용 예제를 작성할 때, 어떤 형식으로 공유하면 좋을까요??

**Comment by iopopoi** [comment]
결과물 실행과정을 영상으로 찍어서 공유하면 좋을 것 같아요.

**Comment by iopopoi** [comment]
영상을 찍은 후에 유튜브를 이용하여 Readme.md에 작성하는 식으로 진행하면 좋을것 같아요.

**Comment by huskycat1202** [comment]
그럼 영상을 찍고 유투브에 올릴게요!
