### ISSUE TITLE
입력창 개선방안

### ISSUE THREAD

**Issue by iopopoi** [iopopoi/tudac#6]
심심해?의  입력칸에서 입력이 여러개일 경우 드래그로 이전의 입력을 확인하는데
드래그가 잘 이루어 지지 않습니다.  어떻게 개선하는 것이 좋을까요?

**Comment by kjmin622** [comment]
윗키랑 아랫키로 이동할 수 있도록 구현해볼게요

**Comment by kjmin622** [comment]
구현했습니다
