### ISSUE TITLE
어디가 페이지 하단부 Read More 링크가 작동하지 않습니다.

### ISSUE THREAD

**Issue by kjmin622** [iopopoi/tudac#7]
Read More 버튼을 누르면 page not found 에러 사이트로 이동됩니다.
![image](https://user-images.githubusercontent.com/50573808/85557108-71c4e200-b662-11ea-93b8-1d169d65bc08.png)

**Comment by iopopoi** [comment]
주소를 혹시 잘못 연결한것은 아닌지 확인해봐야 할것 같아요.

**Comment by Lee-SungMin** [comment]
해결 완료했습니다. 피드백 감사합니다!

**Comment by Lee-SungMin** [comment]
해결 완료했습니다. 피드백 감사합니다!
