### ISSUE TITLE
README.md에서 wiki로 참조하는 링크가 잘못되어 있습니다.

### ISSUE THREAD

**Issue by rasauq1122** [iopopoi/tudac#9]
![image](https://user-images.githubusercontent.com/54990367/85570664-8018fb00-b66e-11ea-8fbc-390d5e44e9e9.png)

위 사진에서 wiki의 링크가 잘못 참조되어 있습니다. 확인 바랍니다.

**Comment by kjmin622** [comment]
해결했습니다
